### ISSUE TITLE
Kafka消息消费失败重试一定次数后怎么处理

### ISSUE THREAD

**Issue by WYUSIG** [flycash/interview-baguwen#5]
我想问实际开发中，如果消息消费失败重试一定次数后，是业务端自己把消息发到另外一个Topic，然后人工介入处理这个Topic还是怎么做法?

**Comment by flycash** [comment]
我一般只回答面试问题=。=
这个问题，我只能说取决于你业务上想怎么做。一般我是建议设计一个统一的机制来处理。比如说，如果你认为重复几次消费都失败，是不可挽回的，那就只能人工介入，告警就可以；
但是如果你觉得，我这个失败只是暂时的，比如说你网络问题导致短时间内几次重试都失败了，但是后面是可能消费成功的，那你就要考虑统一的延后再次处理的机制。
消费者自己发到别的topic可以，也可以自己丢到数据库里面。总之就是先放一个地方，后面再来重试。

所以完全取决于你觉得重试失败几次以后，还能不能挽回。
