### ISSUE TITLE
GC 算法：“用复制算法，内存利用率也可以超过50%”的疑问

### ISSUE THREAD

**Issue by dongguabai** [flycash/interview-baguwen#8]
“例如我100M对象，存活的有10M。那么我就只需要10M来装存活对象”这个前提是不是就是有问题的，

100M对象，存活范围是[0,100]，那么复制空间肯定也要是100M吧，相当于100M空间用来复制，100M用来存储对象，是如何算出使用率可以超过50%的呢

**Comment by flycash** [comment]
你可以参考JVM年轻代的划分，典型的超过50%
