### ISSUE TITLE
三色标记法

### ISSUE THREAD

**Issue by carteruu** [flycash/interview-baguwen#9]
原文："黑色代表存活对象，灰色代表正在标记中，白色表示死亡对象"
黑色代表对象自身及其引用（子节点）都被扫描过了；灰色代表自身被扫描过，但未扫描完其引用；白色代表自身及其引用都还没有被扫描。

**Comment by carteruu** [comment]
大明老师好

**Comment by flycash** [comment]
对，我就是指你说的那个
